# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'fauth' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for fauth

  # Required by RNFirebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  target 'fauthTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'fauth-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for fauth-tvOS

  target 'fauth-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
